### PR TITLE
Remove deprecation warning (pins coffee-script dep at 1.12.6)

### PR DESCRIPTION
**Pull request by mikermcneil**
For more information, see:

• https://github.com/gruntjs/grunt/issues/1556#issuecomment-315189532 
• https://github.com/jashkenas/coffeescript/pull/4543
• https://github.com/jashkenas/coffeescript/commit/f661f91323e4873bc581e98f5bec105f53c372b3

### CODE REVIEW

**Comment by graingert** [comment]
pretty sure 1.12.6 is still deprecated.

**Comment by graingert** [comment]
@vladikoff can you take a look at this?

**Comment by graingert** [comment]
@vladikoff is grunt dead?

**Comment by vladikoff** [comment]
@shama thoughts on this? I am kinda against pinning this version

**Comment by graingert** [comment]
Would be better to move to the not deprecated version

**Comment by graingert** [comment]
@vladikoff I'm going with https://github.com/gruntjs/grunt/pull/1621

**Pull request closed without merging**
