### PR TITLE
Indicate in package.json that Node.js 4 or newer is required

### PR DESCRIPTION
**Pull request by realityking**
Follow up to #1636

### CODE REVIEW

**Comment by vladikoff** [comment]
Thanks!

**Comment by shama** [comment]
Won't this now give people a hard error if they patch bump Grunt while on an older version of Node? 

FWIW, I didn't include this change on purpose as we only passively deprecated support for older versions of Node. In other words, we didnt make a change that broke Grunt on older versions of Node, we just no longer support it.

**Comment by vladikoff** [comment]
> Won't this now give people a hard error if they patch bump Grunt while on an older version of Node?

@shama I don't think `engines` ever hard errored. Have you seen that happen?

**Comment by shama** [comment]
It looks like it's just been broken in npm for 2 years: https://github.com/npm/npm/issues/12486 But I was incorrect, not a hard error with npm but it should give a warning.

With yarn, it will hard error though (Im running Node 10 and created a test package with Node >= 12):
screen shot 2018-06-19 at 8 34 03 am

I still don't think we should make this change yet as it is technically not true. Grunt 1.0.3 still does work with older versions of Node.

**Comment by vladikoff** [comment]
Ah Yarn, sure 

reverted https://github.com/gruntjs/grunt/pull/1644

**Comment by vladikoff** [comment]
Thanks @shama !

**Comment by shama** [comment]
Thank you @vladikoff!

**Comment by realityking** [comment]
I didn't realize this was a passive deprecation. The changelog simply states

> Drop support for Node 0.10 and 0.12

Personally, I think passive deprecations are a bad idea. They simply mean things will keep working until some change gets added where things stop working and the user has no indication what just happened. IMO It's much better to make a hard cut and to shout it from the rooftops.

**Comment by DanielRuf** [comment]
Imo this should be a new major release then. Also Node.js 4 reached its EOL. Using it is not a good idea unless you do not care about security.

**Comment by shama** [comment]
[1. MAJOR version when you make incompatible API changes](https://semver.org/)

We did not make *any* API change. We simply removed Node `0.10` and `0.12` from our continuous integrations.

It's not our job to push people to upgrade Node. They can decide for themselves.

The worse thing that will happen with this change is a future version of Grunt *might* break on an older version of Node.js that very few people use and very few even support. If that unlikely event ever happens, at that time that person can then choose to upgrade Node to use the newer version of Grunt or not.

**Comment by DanielRuf** [comment]
Well, the engines field is generella for enforcing this, removing the entries from the CI config should be enough ;-)

**Comment by shama** [comment]
> incompatible **API** changes

The CI config files for this project are not part of Grunt's API.

As I stated earlier, the engines field doesn't even work. So even with this change, it won't do what you are expecting.

**Pull request merged**
