### PR TITLE
update to latest cli 1.2.0

### PR DESCRIPTION
**Pull request by vladikoff**
@shama r?

### CODE REVIEW

**Comment by vladikoff** [comment]
@shama I guess we should wait for the shared lib and publish 1.2 of the cli?

**Comment by shama** [comment]
Yep! I'll have a PR shortly.

**Comment by vladikoff** [comment]
I will need to update this to 1.2.0 of cli...

**Comment by vladikoff** [comment]
@shama ok this is good to go, now we just need to update the rc1 lib versions right?

**Comment by shama** [comment]
@vladikoff Yep!

**Pull request merged**
