### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by XhmikosR**
PS. Would be nice if we bumped all dependencies eventually. Although, node.js 0.8 support might break...

### CODE REVIEW

**Comment by cowboy** [comment]
@sindresorhus why did you merge this commit? It seems superfluous and possibly problematic.

/cc @tkellen @vladikoff

**Comment by cowboy** [comment]
There's absolutely no reason the sort dependencies in `package.json` unless npm does that explicitly, in which case that should be explained in the commit. Also, these should all be separate PRs, and not combined into one, because they are all touching different areas of the project.

**Comment by XhmikosR** [comment]
What is problematic exactly?

**Comment by XhmikosR** [comment]
Yes, npm sorts the dependencies.

**Comment by cowboy** [comment]
There's no reason to change the dependency sorting unless we're actually making a change to `package.json` and that happens as a matter of course.

**Comment by XhmikosR** [comment]
Like I said, this is npm's behavior.

**Comment by cowboy** [comment]
@XhmikosR the problem is less that you made this PR (which should have been 3 separate PRs) but more that it was merged into master in its current state. It's a lot to change for one PR, especially since it's not closing any specific issues in our issue tracker.

**Comment by XhmikosR** [comment]
It's simply consistency changes, that is all.

I was in the process of updating the dependencies, hence the sorting. But that didn't go well since I get 2 failed tests.

Anyway, separate PRs are nice and all, but not in this case.

**Comment by sindresorhus** [comment]
> There's absolutely no reason the sort dependencies in package.json unless npm does that explicitly, in which case that should be explained in the commit

It's done so a PR that actually bumps the dependencies won't be messy. npm sorts deps by default.

**Comment by cowboy** [comment]
In that case, it would be nice to have a separate PR with a commit that explains this clearly.

**Comment by sindresorhus** [comment]
@cowboy Yeah, sure. I just assumed it was common knowledge.

**Comment by cowboy** [comment]
@sindresorhus consider that the commit is part of a multi-commit PR where each PR seems unrelated.

Also, the commit is titled "Sort dependencies by name." with no other explanation—but if you look at [the commit](https://github.com/gruntjs/grunt/commit/02f5d4f17222b87e7880aab32d275b90af907f78) you'll see that more has changed than just sorting the dependencies by name, which is possibly suspicious (eg. changing the `url` from `http://` to `https://`).

It would be unfortunate if, during the sorting, a dependency version or some other important metadata was changed.

**Comment by sindresorhus** [comment]
Not interested in bikeshedding. I'll just halt my activity on this repo.

**Comment by phietrt** [comment]
I opted to do this in 3 commits but this is basically bikeshedding. Please stop discussing this and do something useful (like the 110 issues)

 > I'll just halt my activity on this repo.

Seems like you just losed another collaborator :(

**Comment by cowboy** [comment]
Thanks for all your hard work @sindresorhus!

**Comment by cowboy** [comment]
@phietrt / @XhmikosR, in case you couldn't tell, I don't have time to close issues on Grunt right now.

To that end, I've been actively looking for a new maintainer for months, but my search to find someone who both wants to maintain Grunt, has the skills to do so, and understands how decisions made in the project can impact the community hasn't been particularly successful.

Regarding your contributions, while I appreciate them, I want to be able to look at any particular commit in the project and understand why that commit was merged. Without a descriptive issue or commit message or a corresponding issue, these three commits seem mostly superfluous, and just increase the amount of work it takes to maintain the project without creating measurable benefit to the project. I'm not suggesting that you don't contribute. However, consider that every issue and PR has to be reviewed, which takes time that could be better spent elsewhere.

Regarding bikeshedding, and this goes for both you and @sindresorhus, you don't have to like what a project owner or maintainer has to say about your activity on a project, but you should at least respect their opinion, and try to understand what might have motivated them to offer up that opinion. It's healthy to be open to having one's ideas challenged, and I can't think of a better way than to contribute to an open source project.

**Comment by sindresorhus** [comment]
I respect your opinion. Was just saying I don't have time to discuss and would rather just not participate in this repo :)

**Comment by XhmikosR** [comment]
@cowboy: you make something out of nothing here. I don't think I disrespected your choice or anything.

This was already merged anyway. Had you spoken sooner, I could have changed the commit messages, maybe. Because, like you, as you say, don't have time to do everything, which is completely understandable, I prefer not to spend a lot of time for simple changes like these.

**Pull request merged**
