### PR TITLE
Update findup-sync to 0.3.0 and lodash to 3.10.1

### PR DESCRIPTION
**Pull request by paladox**
Updating findup-sync to 0.3.0 because it currently complains that it is using a deprecated release of lodash in it.

Updating will fix the problem.

### CODE REVIEW

**Comment by JJ** [comment]
:+1:

**Comment by andrewaustin** [comment]
+1

**Comment by kayabendroth** [comment]
+1 for removing the nasty warning during builds.

**Comment by paulfelton** [comment]
+1

**Comment by kmgilbert100** [comment]
+1

**Comment by vladikoff** [comment]
https://github.com/gruntjs/grunt/pull/1422#issuecomment-171990772

**Pull request merged**
