### PR TITLE
Fix #1419  #1384 : Update lodash & find-syncup dependencies

### LINKED ISSUE #1419: Update lodash dependency
I am getting warning 

```javascript

npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

```

### PR DESCRIPTION
**Pull request by kbouzidi**
Update lodash dependency  0.9.2 -> 3.10.1
Update find-syncup dependency 0.1.2->0.3.0

### CODE REVIEW

**Comment by andrewaustin** [comment]
+1

**Comment by saas786** [comment]
+1

**Comment by paulfelton** [comment]
+1

**Comment by kayabendroth** [comment]
This duplicates https://github.com/gruntjs/grunt/pull/1406.

**Comment by kajyr** [comment]
+1

**Comment by vladikoff** [comment]
Locked. we are aware of this issue and will get to it when we can. it is not as easy as just bumping a version #

**Comment by shama** [comment]
Dependencies have been updated. Thank you for your patience.

**Pull request closed without merging**
