### PR TITLE
tests: test Node.js 6, 8 and 10

### PR DESCRIPTION
**Pull request by DanielRuf**
All others reached their EOL and do not get any (security) patches.

### CODE REVIEW

**Comment by DanielRuf** [comment]
See https://github.com/nodejs/Release/blob/master/README.md

**Comment by shama** [comment]
Thanks for the PR! We typically decide as a team on which versions of Node.js we support based on usage statistics and the effort it takes to continue supporting those versions.

Node `0.10` and `0.12` have low usage and high effort to support, so we no longer support those.
Node `>=4` currently has significant usage and low effort to support, so we'll continue supporting those versions for the time being.

**Comment by DanielRuf** [comment]
> Node >=4 currently has significant usage and low effort to support, so we'll continue supporting those versions for the time being.

Can you share the sources where we can see the numbers to decide this in other projects? Would be very helpful.

**Comment by shama** [comment]
No problem! https://nodesource.com/node-by-numbers is a good source as well as https://semaphoreci.com/blog/2017/11/22/nodejs-versions-used-in-commercial-projects-in-2017.html

**Pull request closed without merging**
