### PR TITLE
Add Node.js v7 and v8 to Travis CI

### PR DESCRIPTION
**Pull request by ryysud**
Add support for Node.js v7 and v8.
Updated .travis.yml.

### CODE REVIEW

**Comment by shama** [comment]
Hmm interesting, it looks like `nvm` doesn't support Node 0.10, 0.12, iojs anymore? I wonder what the current Node usage stats are and if we can consider dropping support for those too.

**Comment by ryysud** [comment]
I thought nvm was the cause of the job failure. 
However, when comparing the successful job ([Job #736.1](https://travis-ci.org/gruntjs/grunt/jobs/224567742)) and the failed job ([Job #737.1](https://travis-ci.org/gruntjs/grunt/jobs/249291273)),
I found that the version of npm is different.
```
Job #736.1 is success :)
$ npm install -g npm
/home/travis/.nvm/v0.10.48/bin/npm -> /home/travis/.nvm/v0.10.48/lib/node_modules/npm/bin/npm-cli.js
npm@4.5.0 /home/travis/.nvm/v0.10.48/lib/node_modules/npm

Job #737.1 is failure :(
$ npm install -g npm
/home/travis/.nvm/v0.10.48/bin/npm -> /home/travis/.nvm/v0.10.48/lib/node_modules/npm/bin/npm-cli.js
npm@5.0.4 /home/travis/.nvm/v0.10.48/lib/node_modules/npm
```

I checked [the document of npm@5.0.4](https://github.com/npm/npm/tree/v5.0.4#important) and found the following sentence.
```
To install an old and unsupported version of npm that works on node v0.12 and prior, clone the git repo and dig through the old tags and branches.
```

I thought that it was caused by using the latest version of npm by "npm install - g npm".

What do you think about this ?

**Comment by shama** [comment]
Thanks for the research @ryysud! My understanding is we'll need to install the version of npm that corresponds with the version of Node, rather than latest? We've had to do this in the past, I can take care of it and then merge this PR in.

**Comment by ryysud** [comment]
Yes. I believe that you need to install a version of npm that corresponds to the version of Node, not a latest version.

**Comment by ryysud** [comment]
Thanks!
> I can take care of it and then merge this PR in.

**Comment by vladikoff** [comment]
yay

**Pull request merged**
